In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

In [2]:
df = pd.read_csv('/Users/KeanuVentura/Desktop/dataset.csv')

df.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,numVotes,cast
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",Christopher Nolan,Christopher Nolan,8.8,2820282,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan",8.7,2533925,"Matthew McConaughey, Anne Hathaway, Michael Ca..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...",9.1,3171353,"Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",James Cameron,James Cameron,7.9,1499045,"Sam Worthington, Zoe Saldaña, Sigourney Weaver..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",Joss Whedon,"Joss Whedon, Zak Penn",8.0,1559461,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ..."

In [3]:
df.describe()

,id,vote_average,vote_count,revenue,runtime,budget,popularity,averageRating,numVotes
count,4.384050e+05,438405.000000,438405.000000,4.384050e+05,438405.000000,4.384050e+05,438405.000000,438405.000000,4.384050e+05
mean,4.983967e+05,3.585993,48.612039,1.660893e+06,66.412518,6.496583e+05,2.184031,6.222034,3.137063e+03
std,3.700811e+05,3.152592,511.444166,2.619621e+07,64.204582,7.410229e+06,11.315440,1.311154,3.414151e+04
min,2.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.000000,5.000000e+00
25%,2.112210e+05,0.000000,0.000000,0.000000e+00,15.000000,0.000000e+00,0.600000,5.400000,2.400000e+01
50%,4.212140e+05,4.512000,1.000000,0.000000e+00,80.000000,0.000000e+00,0.850000,6.300000,7.100000e+01
75%,7.167380e+05,6.200000,5.000000,0.000000e+00,96.000000,0.000000e+00,1.649000,7.100000,3.290000e+02
max,1.701941e+06,10.000000,34495.000000,2.923706e+09,14400.000000,8.880000e+08,2994.357000,10.000000,3.191840e+06

In [4]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'tconst', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords', 'directors', 'writers', 'averageRating', 'numVotes',
       'cast'],
      dtype='str')

In [5]:
# drop useless columns

In [6]:
titles = df['title']

cols_to_drop = [
    'id',
    'status',
    'homepage',
    'backdrop_path',
    'poster_path',
    'tagline',
    'overview',
    'tconst',
    'vote_count',
    'vote_average',
    'numVotes',
    'popularity'
]

df = df.drop(columns=cols_to_drop)

df.head()

,title,release_date,revenue,runtime,adult,budget,original_language,original_title,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,cast
0,Inception,2010-07-15,825532764,148,False,160000000,en,Inception,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",Christopher Nolan,Christopher Nolan,8.8,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W..."
1,Interstellar,2014-11-05,701729206,169,False,165000000,en,Interstellar,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan",8.7,"Matthew McConaughey, Anne Hathaway, Michael Ca..."
2,The Dark Knight,2008-07-16,1004558444,152,False,185000000,en,The Dark Knight,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...",9.1,"Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,Avatar,2009-12-15,2923706026,162,False,237000000,en,Avatar,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",James Cameron,James Cameron,7.9,"Sam Worthington, Zoe Saldaña, Sigourney Weaver..."
4,The Avengers,2012-04-25,1518815515,143,False,220000000,en,The Avengers,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",Joss Whedon,"Joss Whedon, Zak Penn",8.0,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ..."

In [7]:
# replace 0's with np.nas, clip runtime to a maximum of 300 mins (5hours)

In [8]:
cols = ['budget', 'revenue', 'runtime']
df[cols] = df[cols].replace(0, np.nan)

df['runtime'] = df['runtime'].clip(upper=300)

df = df.dropna(subset=['averageRating'])

In [9]:
# explode genres

In [10]:
df['genres'] = df['genres'].str.split(', ')

genres_dummies = (
    df['genres']
    .explode()
    .str.get_dummies()
    .groupby(level=0)
    .sum()
)

df = df.join(genres_dummies)
df = df.drop(columns=['genres'])

In [11]:
# split directors into top 50 and others create director_count

In [12]:
top_directors = df['directors'].value_counts().head(50).index

df['director_clean'] = df['directors'].apply(
    lambda x: x if x in top_directors else 'Other'
)

df['director_count'] = df['directors'].map(df['directors'].value_counts())

df = pd.get_dummies(df, columns=['director_clean'])
df = df.drop(columns=['directors'])

In [13]:
# date to year, only release years 2024 or less

In [14]:
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

df['release_year'] = df['release_date'].dt.year

df = df.drop(columns=['release_date'])
df = df[df['release_year'] <= 2024]

In [15]:
# split languages into top 50 and others

In [16]:
top_langs = df['original_language'].value_counts().head(10).index

df['lang_clean'] = df['original_language'].apply(
    lambda x: x if x in top_langs else 'Other'
)

df = pd.get_dummies(df, columns=['lang_clean'])
df = df.drop(columns=['original_language'])

In [17]:
# fill in missing budget and revenue

In [18]:
df['budget_missing'] = df['budget'].isna().astype(int)
df['revenue_missing'] = df['revenue'].isna().astype(int)
df['runtime_missing'] = df['runtime'].isna().astype(int)

df[['budget', 'revenue', 'runtime']] = df[['budget', 'revenue', 'runtime']].fillna(
    df[['budget', 'revenue', 'runtime']].median()
)

In [19]:
# drop other columns that we might revisit later

In [20]:
cols_to_drop = [
    'title',
    'original_title',
    'production_companies',
    'production_countries',
    'spoken_languages',
    'keywords',
    'writers'
]

df = df.drop(columns=cols_to_drop)

In [21]:
# keep top actors and most frequent

In [22]:
df['cast'] = df['cast'].str.split(', ').str[:3]

top_actors = (
    df['cast']
    .explode()
    .value_counts()
    .head(50)
    .index
)

df['cast_clean'] = df['cast'].apply(
    lambda actors: [a for a in actors if a in top_actors] if isinstance(actors, list) else []
)

cast_dummies = (
    df['cast_clean']
    .explode()
    .str.get_dummies()
    .groupby(level=0)
    .sum()
)

df = df.join(cast_dummies)
df = df.drop(columns=['cast', 'cast_clean'])

In [23]:
# baseline lin reg

In [24]:
X = df.drop(columns=['averageRating'])
y = df['averageRating']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R^2:", r2_score(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred))

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [26]:
# random forest

In [ ]:
rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("RF R^2:", r2_score(y_test, y_pred_rf))
print("RF RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

In [ ]:
importances = pd.Series(rf.feature_importances_, index=X.columns)
importances.sort_values(ascending=False).head(15)

In [ ]:
# tune random forest

In [ ]:
rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=25,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("RF R^2:", r2_score(y_test, y_pred_rf))
print("RF RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))